### ISSUE TITLE
Segmentation fault when calling comm->get_message()

### ISSUE THREAD

**Issue by ramygad** [fast-project/fast-lib#11]
Hi,
I got a segmentation fault when calling comm->get_message().
I have attached the gdb  backtrace 

[fast-lib_error1.txt](https://github.com/fast-project/fast-lib/files/50916/fast-lib_error1.txt)

Best Regards,

Ramy

**Comment by timohl** [comment]
Hello.

Line 49 states: 

> #5  0x0000000000519fc6 in fast::MQTT_communicator::get_message (this=0x0, topic=..., duration=...)

So `this` seems to be a null pointer.
Can you check if `comm` is properly initialized?

Kind regards
Tim

**Comment by ramygad** [comment]
Thank you Tim.

This solve my problem
