### ISSUE TITLE
fastlib/src/mqtt_communicator.cpp:182:51: error: passing ‘const fast::MQTT_communicator’ as ‘this’ argument

### ISSUE THREAD

**Issue by ramygad** [fast-project/fast-lib#29]
while compiling fastlib as a part of  scheduler mqtt interface

I go the following errors in the attached file

[log.txt](https://github.com/fast-project/fast-lib/files/383907/log.txt)

**Comment by timohl** [comment]
There have been recent changes in the fast-lib concerning const-ness of several methods.
However, I cannot reproduce this error.
Maybe, clearing the build directory and starting a fresh new build could help.
I suspect cmake to not have updated the mosquitto part of fast-lib in your build.

**Comment by ramygad** [comment]
Deleting the project and starting from a fresh one solved the problem.

Thank you :-)
